<%@ page contentType="text/html;charset=UTF-8" language="java" %>
    <%@ taglib uri="jakarta.tags.core" prefix="c" %>
        <!DOCTYPE html>
        <html lang="en">

        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>SmartCampus - Report History</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
                rel="stylesheet">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
            <style>
                body {
                    background-color: #f8f9fa;
                    font-family: 'Inter', sans-serif;
                }

                .navbar {
                    background: linear-gradient(135deg, #4361ee, #3f37c9);
                }

                .table-container {
                    background: white;
                    border-radius: 15px;
                    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.05);
                    padding: 2rem;
                    margin-top: 2rem;
                }
            </style>
        </head>

        <body>
            <nav class="navbar navbar-expand-lg navbar-dark mb-4">
                <div class="container">
                    <a class="navbar-brand fw-bold" href="summary"><i class="fas fa-university me-2"></i>SmartCampus
                        Reports</a>
                    <div class="navbar-nav">
                        <a class="nav-link" href="summary">Dashboard</a>
                        <a class="nav-link" href="student">Student Report</a>
                        <a class="nav-link active" href="logs">History</a>
                    </div>
                </div>
            </nav>

            <div class="container">
                <div class="table-container">
                    <h3 class="fw-bold mb-4"><i class="fas fa-history me-2 text-primary"></i>Report Generation History
                    </h3>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Type</th>
                                <th>Generated At</th>
                                <th>Summary</th>
                                <th>Generated By</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <c:forEach var="log" items="${logs}">
                                <tr>
                                    <td>${log.id}</td>
                                    <td><span class="badge bg-primary">${log.reportType}</span></td>
                                    <td>${log.generatedAt}</td>
                                    <td><code>${log.dataSummary}</code></td>
                                    <td>${log.generatedBy}</td>
                                    <td>
                                        <a href="delete?id=${log.id}" class="btn btn-sm btn-danger"
                                            onclick="return confirm('Are you sure you want to delete this log?')">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            </c:forEach>
                        </tbody>
                    </table>
                </div>
            </div>
        </body>

        </html>